### ISSUE TITLE
1 - Création de la ressource dans CosmoDB dans Azure

### ISSUE THREAD

**Issue by Obsywon** [Obsywon/EscapadeM2#9]

**Comment by GaetanKorpys** [comment]
Done 
Ressource User ( Id généré automatiquement )  : 
{
    "Id": "d37db7ce-ae60-4ab1-825b-981729680883",
    "BirthDate": "1990-01-01",
    "Email": "john.doe@example.com",
    "Genre": "Male",
    "LastName": "Doe",
    "Name": "John",
    "Password": "password123"
}
